#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SectionId {
    Overview,
    Foundations,
    Experience,
    Education,
    Skills,
    Interests,
    Links,
    Install,
}

pub struct Resume {
    pub name: &'static str,
    pub headline: &'static str,
    pub location: &'static str,
    pub website: &'static str,
    pub sections: Vec<Section>,
}

pub struct Section {
    pub id: SectionId,
    pub title: &'static str,
    pub description: &'static str,
    pub items: Vec<Entry>,
}

pub struct Entry {
    pub eyebrow: &'static str,
    pub title: &'static str,
    pub subtitle: &'static str,
    pub summary: &'static str,
    pub bullets: &'static [&'static str],
    pub meta: &'static [&'static str],
    pub url: Option<&'static str>,
    pub command: Option<&'static str>,
}

pub fn resume() -> Resume {
    Resume {
        name: "Shaan Patel",
        headline: "AI researcher, operator, and systems builder across crypto, public goods, and technical storytelling.",
        location: "New York, NY",
        website: "https://shaanpatel.dev",
        sections: vec![
            Section {
                id: SectionId::Overview,
                title: "Overview",
                description: "A fast snapshot of the work, worldview, and current focus areas behind the CV.",
                items: vec![
                    Entry {
                        eyebrow: "Current",
                        title: "What I do",
                        subtitle: "Research, operations, product sense, and technical storytelling",
                        summary: "I work at the boundary between technical systems, institutional design, and story. The through-line is making complicated environments feel legible, navigable, and alive.",
                        bullets: &[
                            "Currently building around confidential stablecoins, verifiable AI, and trusted execution environments.",
                            "Comfortable moving between research, partnerships, docs, onboarding, and product communication.",
                            "Care deeply about systems that feel rigorous without losing beauty or humanity.",
                        ],
                        meta: &["AI", "crypto", "protocols", "operator"],
                        url: Some("https://shaanpatel.dev"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Lens",
                        title: "How I think",
                        subtitle: "Sacred economics, governance design, and secure intelligence",
                        summary: "My interests span sacred economics, secure and verifiable AI, public goods, governance design, and decentralized networks. I like building tools that make high-complexity domains easier to reason about.",
                        bullets: &[
                            "Research-minded builder with an eye for aesthetics in systems and interface design.",
                            "Grounded by permaculture, DIY engineering, running, biking, cooking, yoga, soccer, chess, Go, and Catan.",
                        ],
                        meta: &["research", "governance", "design"],
                        url: Some("https://shaanpatel.dev"),
                        command: None,
                    },
                ],
            },
            Section {
                id: SectionId::Foundations,
                title: "Foundations",
                description: "The long-view themes and principles that shape how I choose work and collaborators.",
                items: vec![
                    Entry {
                        eyebrow: "Education + research",
                        title: "Economics and data science foundation",
                        subtitle: "Columbia University with sustainability and impact-oriented research",
                        summary: "My academic background combines economics, business analytics, and research spanning sustainable development and environmental impact questions.",
                        bullets: &[
                            "Research topics included growth and development issues in Kenya.",
                            "Also studied pollution indicators and infant mortality relationships in India.",
                        ],
                        meta: &["economics", "data", "systems thinking"],
                        url: None,
                        command: None,
                    },
                    Entry {
                        eyebrow: "Builder philosophy",
                        title: "Make complexity navigable",
                        subtitle: "Technical systems, institutional design, and narrative clarity",
                        summary: "I am most energized by products and protocols that turn messy coordination problems into clear, usable experiences for builders, researchers, and communities.",
                        bullets: &[
                            "I value strong research paired with clear developer onboarding.",
                            "I like work that connects theory, implementation, and practical adoption.",
                        ],
                        meta: &["clarity", "coordination", "adoption"],
                        url: None,
                        command: None,
                    },
                ],
            },
            Section {
                id: SectionId::Experience,
                title: "Experience",
                description: "Selected roles across AI, crypto, public goods, and ecosystem building.",
                items: vec![
                    Entry {
                        eyebrow: "2025-2026",
                        title: "Halo Labs",
                        subtitle: "Co-Founder and COO",
                        summary: "Leading research around confidential stablecoins, verifiable AI, trusted execution environments, partnerships, docs, and developer onboarding.",
                        bullets: &[
                            "Led research on verifiable AI using TEEs and zk-proofs.",
                            "Maintained website and key technical documentation.",
                            "Onboarded developers to the Halo light client.",
                            "Led collaborations with providers like Phala and Fairblocks.",
                        ],
                        meta: &["verifiable AI", "TEEs", "zk", "ops"],
                        url: Some("https://docs.halo-labs.xyz/"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "2024-2025",
                        title: "NPC Capital",
                        subtitle: "Full Stack Developer and Researcher",
                        summary: "Worked inside a liquid crypto fund partnered with Polygon, building investor tooling and cross-chain research infrastructure.",
                        bullets: &[
                            "Built a heads-up display for fund investors.",
                            "Established cross-chain data pipelines for investment decisions.",
                            "Worked with Hyperliquid validators to test real yield strategies.",
                        ],
                        meta: &["full-stack", "data pipelines", "research"],
                        url: None,
                        command: None,
                    },
                    Entry {
                        eyebrow: "Ecosystem",
                        title: "Public Goods + Open Source",
                        subtitle: "Celo, Dream DAO, Eco DAO, Solana Foundation",
                        summary: "Worked across open-source education, public-goods strategy, DAO governance, and ecosystem coordination to help communities turn ideas into usable systems.",
                        bullets: &[
                            "Solana Foundation: updated developer docs with clearer wording and versioning.",
                            "Celo: built content pipelines and public-goods strategy around open-source initiatives.",
                            "Dream DAO: co-stewarded a community of about 100 young builders and hosted 40+ online plus 4 IRL gatherings.",
                            "Eco DAO: onboarded organizations and individuals, implemented governance tooling, and supported NFT launches.",
                        ],
                        meta: &["public goods", "education", "governance"],
                        url: Some("https://github.com/Halo-Labs-xyz/halo-verus"),
                        command: None,
                    },
                ],
            },
            Section {
                id: SectionId::Education,
                title: "Education",
                description: "Formal training and research background.",
                items: vec![Entry {
                    eyebrow: "University",
                    title: "Columbia University",
                    subtitle: "Economics and Business Analytics",
                    summary: "Economics and business analytics studies with an environmental concentration and research spanning sustainable development and public-impact questions.",
                    bullets: &[
                        "Research: Growth and development issues in Kenya.",
                        "Research: Air vs. water pollution as indicators of infant mortality rates in India.",
                    ],
                    meta: &["economics", "analytics", "research"],
                    url: None,
                    command: None,
                }],
            },
            Section {
                id: SectionId::Skills,
                title: "Skills",
                description: "A compact view of the languages, tools, and ways of working that show up across my projects.",
                items: vec![
                    Entry {
                        eyebrow: "Technical",
                        title: "Languages and tooling",
                        subtitle: "Across product, research, and engineering execution",
                        summary: "Selected tools and languages that recur across my work.",
                        bullets: &[
                            "TypeScript, Python, Rust, Solidity, Pandas.",
                            "Project management and cross-functional coordination.",
                            "Documentation, onboarding, and technical communication.",
                        ],
                        meta: &["TypeScript", "Python", "Rust", "Solidity"],
                        url: None,
                        command: None,
                    },
                    Entry {
                        eyebrow: "Languages",
                        title: "Spoken languages",
                        subtitle: "Useful for global communities and ecosystem work",
                        summary: "I operate across technical and social contexts, so language agility matters.",
                        bullets: &[
                            "English (fluent)",
                            "Gujarati (proficient)",
                            "Hindi (proficient)",
                            "Spanish (proficient)",
                            "Mandarin (conversational)",
                            "French (beginner)",
                        ],
                        meta: &["communication", "community", "global"],
                        url: None,
                        command: None,
                    },
                ],
            },
            Section {
                id: SectionId::Interests,
                title: "Interests + Resources",
                description: "A grounded map of the technical domains, likely trajectories, and project resources shaping the next arc of my work.",
                items: vec![
                    Entry {
                        eyebrow: "Core interests",
                        title: "Where my curiosity compounds",
                        subtitle: "The systems and problem spaces I keep returning to",
                        summary: "These themes recur across my research, operator work, and product instincts. They are the areas where I want to keep building depth.",
                        bullets: &[
                            "Privacy-focused blockchain architecture.",
                            "Stablecoins, DeFi, and payment rails.",
                            "Blockchain analytics and on-chain intelligence.",
                            "Agentic automation and bot systems.",
                            "Trading and execution infrastructure.",
                            "Zero-knowledge proving systems.",
                            "Rust-heavy protocol and client engineering.",
                        ],
                        meta: &[
                            "privacy",
                            "stablecoins",
                            "analytics",
                            "agents",
                            "zk",
                            "Rust",
                        ],
                        url: Some("https://shaanpatel.dev"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Potential",
                        title: "Directions that fit my edge",
                        subtitle: "How these interests could consolidate into long-term positioning",
                        summary: "The strongest forward paths combine privacy, payments, AI assurance, execution systems, and platform architecture in a way that is both technically serious and operationally useful.",
                        bullets: &[
                            "Privacy + payments protocol builder across public EVM rails and private state.",
                            "ZK infrastructure specialist working on SP1, zkEVMs, and proving pipelines.",
                            "Enterprise blockchain analytics product builder.",
                            "Autonomous trading and risk-automation systems builder.",
                            "Crypto-fintech operator focused on real-world payment flows.",
                            "Platform architect unifying Halo-related repos into one cohesive stack.",
                        ],
                        meta: &["positioning", "protocols", "automation", "platform"],
                        url: Some("https://docs.succinct.xyz/"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Project resource map",
                        title: "Local projects informing this direction",
                        subtitle: "A working constellation of protocol, product, and experimentation tracks",
                        summary: "The local project map shows a coherent pattern: privacy infrastructure, light clients, stablecoins, analytics, agents, trading systems, and proving tooling are already present across active explorations.",
                        bullets: &[
                            "Halo-related architecture and client work: HaloVisualizer, halo, halo-light-cli, halolightclient, halositev2, execution_halo.",
                            "Stablecoin and payment direction: halobank, hl, instacash.",
                            "Analytics and data platforms: api-npc, api-npc-stable, api-npc-stablev2, api-npc-diff, apinpc-stable-test, ggscope.",
                            "Agent and bot systems: agentic, bot, botmon.",
                            "Execution infrastructure and integrations: ccxt.",
                            "ZK and client-engineering references: sp1-project-template-main, zecwallet-light-cli-master.",
                            "AI experimentation: ollama.",
                        ],
                        meta: &["resource map", "Halo", "analytics", "bots", "payments"],
                        url: Some("https://docs.halo-labs.xyz/"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "External references",
                        title: "Docs and ecosystems worth tracking",
                        subtitle: "The outside sources most aligned with the roadmap",
                        summary: "These references line up closely with the kinds of systems I am building toward: protocol architecture, proving infrastructure, trading rails, payment networks, Rust client engineering, and deployment surfaces.",
                        bullets: &[
                            "Privacy and protocol architecture: Ethereum developer docs, Polygon CDK docs, Erigon.",
                            "Zero-knowledge and proving: SP1 docs and SP1 GitHub.",
                            "Trading and market infrastructure: CCXT docs and Hyperliquid docs.",
                            "Stablecoins and payments: Circle USDC docs and Tether transparency resources.",
                            "Rust and client engineering: The Rust Book and Tokio docs.",
                            "App and data stack: Next.js docs and Railway docs.",
                            "Funding ecosystem: Gitcoin docs.",
                        ],
                        meta: &["docs", "ecosystem", "learning surface"],
                        url: Some("https://ethereum.org/en/developers/docs/"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Featured repos",
                        title: "Favorite repos and tools",
                        subtitle: "Concrete systems I respect and learn from",
                        summary: "These are strong signals for the taste profile behind the CV: verifiable agents, privacy infrastructure, trading automation, quantum-aware security, and operational crypto tooling.",
                        bullets: &[
                            "Featured repos: HyperClaw, Enclagent, qAegis, LiquidClaw, Halo Verus, TEE Engine, HYPE DCF, Halo Faucet.",
                            "Favorite tools: OpenClaw, IronClaw, ROMA, Hummingbot, Hyperliquid Rust SDK, Hyperliquid Info MCP.",
                            "Across all of them, the shared thread is trusted execution, agentic automation, market infrastructure, and disciplined systems design.",
                        ],
                        meta: &["favorite repos", "tooling", "agent systems"],
                        url: Some("https://github.com/Halo-Labs-xyz/hyperClaw"),
                        command: None,
                    },
                ],
            },
            Section {
                id: SectionId::Links,
                title: "Links",
                description: "Primary places to find my work, writing, and reach me directly.",
                items: vec![
                    Entry {
                        eyebrow: "Website",
                        title: "Portfolio",
                        subtitle: "Live web portfolio",
                        summary: "The visual portfolio version of this CV.",
                        bullets: &[
                            "Best first stop for the broader narrative and interactive presentation.",
                        ],
                        meta: &["primary"],
                        url: Some("https://shaanpatel.dev"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Code",
                        title: "GitHub",
                        subtitle: "Open-source work and repositories",
                        summary: "My main public code profile across research, experiments, and production-facing projects.",
                        bullets: &[
                            "Best place to browse repositories, prototypes, and technical artifacts directly.",
                        ],
                        meta: &["github"],
                        url: Some("https://github.com/Epistetechnician"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Network",
                        title: "LinkedIn",
                        subtitle: "Professional background and contact",
                        summary: "Professional profile covering experience, education, and a familiar place to connect.",
                        bullets: &[
                            "Useful for recruiters, collaborators, and anyone looking for a concise career snapshot.",
                        ],
                        meta: &["linkedin"],
                        url: Some("https://www.linkedin.com/in/shaan-patel21/"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Social",
                        title: "X",
                        subtitle: "Short-form ideas and public updates",
                        summary: "A lightweight feed for thoughts, experiments, and public-facing commentary.",
                        bullets: &[
                            "Good place to follow current interests and shareable work in progress.",
                        ],
                        meta: &["x"],
                        url: Some("https://x.com/epistetechnic"),
                        command: None,
                    },
                    Entry {
                        eyebrow: "Chat",
                        title: "Telegram",
                        subtitle: "@epistetechnician",
                        summary: "Direct handle for quick reach-outs and conversations.",
                        bullets: &[
                            "Best when you want to contact me directly in a lower-friction channel.",
                        ],
                        meta: &["telegram"],
                        url: Some("https://t.me/epistetechnician"),
                        command: None,
                    },
                ],
            },
            Section {
                id: SectionId::Install,
                title: "Install",
                description: "How to install or distribute the terminal CV once the repository is published.",
                items: vec![
                    Entry {
                        eyebrow: "Cargo",
                        title: "Install from source via Cargo",
                        subtitle: "Best developer-friendly default",
                        summary: "This path works as soon as the repository is public and is the cleanest fallback even before release automation is live.",
                        bullets: &[
                            "Installs the `spatel` binary directly from the repository.",
                            "Ideal for contributors or anyone already using Rust tooling.",
                        ],
                        meta: &["source install"],
                        url: Some("https://github.com/Epistetechnician/spatel-cv"),
                        command: Some(
                            "cargo install --git https://github.com/Epistetechnician/spatel-cv.git --bin spatel",
                        ),
                    },
                    Entry {
                        eyebrow: "Curl",
                        title: "Install latest release binary",
                        subtitle: "One-command install for macOS and Linux",
                        summary: "The included installer resolves the current platform, downloads the latest GitHub release archive, and places `spatel` into your local binary directory.",
                        bullets: &[
                            "Supports macOS (Intel and Apple Silicon) and Linux x86_64 release builds.",
                            "Designed to keep the install path simple for non-Rust users.",
                        ],
                        meta: &["release install"],
                        url: Some(
                            "https://raw.githubusercontent.com/Epistetechnician/spatel-cv/master/install.sh",
                        ),
                        command: Some(
                            "curl -fsSL https://raw.githubusercontent.com/Epistetechnician/spatel-cv/master/install.sh | sh",
                        ),
                    },
                    Entry {
                        eyebrow: "GitHub",
                        title: "Download release artifact manually",
                        subtitle: "Good for power users or packaging experiments",
                        summary: "You can also fetch the matching release artifact directly and place the binary wherever you prefer.",
                        bullets: &[
                            "Useful when you want to pin a version or inspect the release files yourself.",
                        ],
                        meta: &["manual"],
                        url: Some("https://github.com/Epistetechnician/spatel-cv/releases"),
                        command: Some(
                            "gh release download --repo Epistetechnician/spatel-cv --pattern \"spatel-*\"",
                        ),
                    },
                ],
            },
        ],
    }
}
